### ISSUE TITLE
Offer Translation help

### ISSUE THREAD

**Issue by Jawkx** [geekxh/hello-algorithm#22]
Send me an Email or pm me on wechat(id: kx_jaw) if you still need translation from Chinese to English for your content. I have nothing much to do now

**Comment by mjh001** [comment]
get it thanks------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;JAW&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月12日(星期三) 上午10:53
收件人:&nbsp;&quot;geekxh/hello-algorithm&quot;<hello-algorithm@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[geekxh/hello-algorithm] Offer Translation help (#22)

**Comment by geekxh** [comment]
THK
