### ISSUE TITLE
非常好

### ISSUE THREAD

**Issue by zzzpppy** [geekxh/hello-algorithm#30]

**Comment by zky001** [comment]
必须得star一下

**Comment by zky001** [comment]
![image](https://user-images.githubusercontent.com/9131265/90728982-6e637500-e2f8-11ea-9441-efb3b982a0c6.png)

**Comment by geekxh** [comment]
thanks

**Comment by geekxh** [comment]
嗯。我决定保留这个

**Comment by quasar1533** [comment]
好！很有精神！
