### ISSUE TITLE
解压需要密码

### ISSUE THREAD

**Issue by FT19960715** [geekxh/hello-algorithm#37]
同标题，求解压密码

**Comment by geekxh** [comment]
本来没有设置密码，但是总是会失效：GRptBtsm。如果不行可加wx： xiaohaosuanfa

**Comment by FT19960715** [comment]
非常感谢分享，密码是正确的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geekxh/hello-algorithm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 上午9:55
收件人:&nbsp;"geekxh/hello-algorithm"<hello-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"氵宓"<1753677963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [geekxh/hello-algorithm] 解压需要密码 (#37)





 
本来没有设置密码，但是总是会失效：GRptBtsm。如果不行可加wx： xiaohaosuanfa
