### ISSUE TITLE
木马？Windows Defender 报毒，云盘下载

### ISSUE THREAD

**Issue by aaazz47** [geekxh/hello-algorithm#40]
百度云盘下载的，文件进度 99% 去除后缀的时候 Windows Defender 报毒。没太注意下载的时候是否有 P2P 加速。

![批注 2020-09-11 105741](https://user-images.githubusercontent.com/19562000/92849811-5033f500-f41e-11ea-9de1-2a0d15545695.jpg)

**Comment by geekxh** [comment]
过万人下载~是你自己的问题哈。换解压软件试试
