### ISSUE TITLE
密码？？？？？？？？

### ISSUE THREAD

**Issue by Castile** [geekxh/hello-algorithm#41]
。。。

**Comment by Daixingdeng** [comment]
你能不能看清楚再说话？？这是我down别人的项目，我看也是关注公众号获取解压密码。别跟个傻吊似的好吗？不想看你别看，说话负责任点，事都理不明白你怼谁呢？？？



---原始邮件---
发件人: "Hongliang Zhu"<notifications@github.com&gt;
发送时间: 2020年9月11日(周五) 下午5:59
收件人: "geekxh/hello-algorithm"<hello-algorithm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [geekxh/hello-algorithm] 密码？？？？？？？？ (#41)




 
要分享就干脆点，纯粹点 ，每一个文件都加个密？？？何必呢？解压一个文件就得上你的公众号发一条信息？别侮辱人好不，要么就别分享。

**Comment by Daixingdeng** [comment]
你谁啊，什么意思？我没分享东西



---原始邮件---
发件人: "Hongliang Zhu"<notifications@github.com&gt;
发送时间: 2020年9月11日(周五) 下午5:59
收件人: "geekxh/hello-algorithm"<hello-algorithm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [geekxh/hello-algorithm] 密码？？？？？？？？ (#41)




 
要分享就干脆点，纯粹点 ，每一个文件都加个密？？？何必呢？解压一个文件就得上你的公众号发一条信息？别侮辱人好不，要么就别分享。
