### ISSUE TITLE
zip文件需要密码，密码是多少呢？

### ISSUE THREAD

**Issue by jinl2011** [geekxh/hello-algorithm#57]
![image](https://user-images.githubusercontent.com/25602802/109613844-b21f1d00-7b6c-11eb-952c-7dc6deca7c9f.png)

**Comment by 1362017995** [comment]
- [x] 我也想问

**Comment by Jijun** [comment]
纯垃圾，各种广告，关注公号。。。

**Comment by Jijun** [comment]
解压密码为：【GRptBtsm】或【elRMzGlY】，密码确认正确，win 建议用 7zip，mac 可以用 ezip/betterzip。

不放密码链接容易崩溃，非故意为难。

**Comment by jinl2011** [comment]
thx
