### ISSUE TITLE
画圈圈问题的答案有误

### ISSUE THREAD

**Issue by toy-lin** [geekxh/hello-algorithm#6]
画圈圈问题里你给的答案是：
> 先把正中间的两个小圆圈涂黑，于是左右两边各剩下了49个圆圈

如果是每次只能划掉一个圈圈，那你的答案没问题。问题是每次能划掉一个或者两个，最终有可能剩下两个圈，被对方一次划掉。

正确的答案应该是每一步都把剩下的圈圈划成3的倍数，并不需要在乎圈圈的排列结构和划掉的顺序。

**Comment by toy-lin** [comment]
抱歉，是我没审好题，题目中给出的条件是一次划掉一个或两个 **相邻** 的圆圈。

**Comment by geekxh** [comment]
THK

**Comment by geekxh** [comment]
希望帮我指正更多的问题～
